on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose up -d
      - name: Sleep while stack is starting
        uses: jakejarvis/wait-action@master
        with:
          time: '2s'
      - name: Run tests
        run: go test ./...
      - name: Run coverage
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
